import { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { Link, useNavigate } from 'react-router-dom';
import { 
  Sparkles, ArrowRight, CheckCircle2, Lock, 
  AlertCircle, RefreshCw, Heart, MessageCircle, 
  Send, Bookmark, Building2, ShoppingBag, Check,
  Upload, Link2, X

} from 'lucide-react';

import { setCredentials } from '../../features/auth/authSlice';

// Automatic Category Visual Presets Generated by AI
const CATEGORY_AI_VISUALS: { [key: string]: { url: string; fallbackTitle: string } } = {
  Footwear: {
    url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1000&auto=format&fit=crop&q=80',
    fallbackTitle: 'Velocity Hyper-Glide Runner'
  },
  Apparel: {
    url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=1000&auto=format&fit=crop&q=80',
    fallbackTitle: 'Apex Leather Moto Jacket'
  },
  Electronics: {
    url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80',
    fallbackTitle: 'Studio Noise-Canceling Headphones'
  },
  Beauty: {
    url: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=1000&auto=format&fit=crop&q=80',
    fallbackTitle: 'Noir Absolu Fragrance'
  },
  Fitness: {
    url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1000&auto=format&fit=crop&q=80',
    fallbackTitle: 'Iron-Flex Performance Kettlebell'
  },
  Jewelry: {
    url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=1000&auto=format&fit=crop&q=80',
    fallbackTitle: 'Chrono-Sport Obsidian Watch'
  },
  Home: {
    url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1000&auto=format&fit=crop&q=80',
    fallbackTitle: 'Minimalist Nordic Ceramic Lamp'
  }
};

const AI_STYLE_THEMES = [
  { id: 'kinetic-red', name: '🔥 Kinetic Red High-Contrast', desc: 'Punchy commercial lighting with signature red accent glow' },
  { id: 'urban-dark', name: '🏙️ Urban Reflective Studio', desc: 'Dark marble backdrop with cinematic product spotlight' },
  { id: 'luxury-gold', name: '✨ Luxury Pedestal Staging', desc: 'Warm ambient editorial aesthetic for premium brands' },
  { id: 'clean-white', name: '🤍 High-Key Studio White', desc: 'Ultra-crisp Apple-inspired clean product showcase' }
];

export default function ExplorerFreeAdPage() {
  const { user } = useSelector((state: any) => state.auth);
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const customerType = user?.customerType || 'EXPLORER';

  // Server/DB source of truth for free ad usage
  const freeAdsUsed = user?.freeAdsUsed ?? (user?.freeAdGenerated ? 1 : 0);
  const freeAdsAllowed = user?.freeAdsAllowed ?? 1;
  const isFreeAdUsed = freeAdsUsed >= freeAdsAllowed;

  // Form State
  const [productName, setProductName] = useState('Velocity Hyper-Glide X1');
  const [productDesc, setProductDesc] = useState('Ultra-lightweight carbon fiber running shoe designed for high-mileage athletes.');
  const [category, setCategory] = useState('Footwear');
  const [price, setPrice] = useState('1499');
  const [targetAudience, setTargetAudience] = useState('Marathon runners, urban fitness enthusiasts, streetwear creators');
  const [location, setLocation] = useState('India (Pan-India Metro Cities)');
  
  // Image Options: AI Studio vs User Upload vs Web URL
  const [imageSourceType, setImageSourceType] = useState<'AI_STUDIO' | 'UPLOAD' | 'URL'>('AI_STUDIO');
  const [uploadedImagePreview, setUploadedImagePreview] = useState<string | null>(null);
  const [uploadedFileName, setUploadedFileName] = useState('');
  const [customImageUrl, setCustomImageUrl] = useState('');

  const [selectedStyle, setSelectedStyle] = useState('kinetic-red');
  const [objective, setObjective] = useState('Product Sales & Purchases');
  const [cta, setCta] = useState('Shop Now');

  const [tone, setTone] = useState('High Energy & Urgent');
  const [sellingPoints, setSellingPoints] = useState('Carbon fiber spring plate, 48-hr flash dispatch, 100% money-back guarantee');
  const [promotionalOffer, setPromotionalOffer] = useState('FLAT 30% OFF + Free Express Shipping');
  const [brandName, setBrandName] = useState(user?.companyName || 'Velocity Sports');

  // Generation Workflow State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStep, setGenerationStep] = useState(0);
  const [generatedResult, setGeneratedResult] = useState<any | null>(null);
  const [activePreviewTab, setActivePreviewTab] = useState<'INSTAGRAM' | 'TIKTOK' | 'FACEBOOK'>('INSTAGRAM');
  const [showConversionModal, setShowConversionModal] = useState(false);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      alert("Please upload a valid image file (PNG, JPG, WebP, etc.).");
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      alert("File size exceeds 5MB limit. Please upload an image under 5MB.");
      return;
    }

    setUploadedFileName(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      setUploadedImagePreview(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleRemoveUploadedImage = () => {
    setUploadedImagePreview(null);
    setUploadedFileName('');
  };

  // Auto-update sample product name when category changes
  const handleCategoryChange = (newCat: string) => {
    setCategory(newCat);
    if (CATEGORY_AI_VISUALS[newCat]) {
      setProductName(CATEGORY_AI_VISUALS[newCat].fallbackTitle);
    }
  };

  // Security Check: If user is not an Explorer, redirect them away
  useEffect(() => {
    if (user && customerType === 'B2B') {
      navigate('/b2b');
    } else if (user && customerType === 'B2C') {
      navigate('/b2c');
    }
  }, [user, customerType, navigate]);

  if (!user) {
    return (
      <div className="max-w-md mx-auto py-24 px-6 text-center font-sans">
        <div className="w-16 h-16 rounded-2xl bg-red-50 text-red-600 flex items-center justify-center mx-auto mb-4 border border-red-200">
          <Lock className="w-8 h-8 text-red-600" />
        </div>
        <h1 className="text-2xl font-black text-black font-display">Authentication Required</h1>
        <p className="text-zinc-600 mt-2 text-xs font-medium">Please sign in or create an Explorer account to claim your 1 Free AI advertisement.</p>
        <Link to="/login?redirect=free-ad" className="btn-shimmer inline-block mt-4 px-6 py-3 bg-red-600 text-white rounded-xl text-xs font-black uppercase tracking-wider shadow-md">
          Sign In to Access
        </Link>
      </div>
    );
  }

  // Submit Free Ad Generation
  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();

    if (isFreeAdUsed) {
      alert("Your 1 Free Advertisement has already been claimed. Please choose B2B or B2C in your profile to create more ads.");
      setShowConversionModal(true);
      return;
    }

    setIsGenerating(true);
    setGenerationStep(1);

    setTimeout(() => setGenerationStep(2), 700);
    setTimeout(() => setGenerationStep(3), 1400);

    setTimeout(() => {
      setIsGenerating(false);

      let visualAsset = CATEGORY_AI_VISUALS[category]?.url || CATEGORY_AI_VISUALS['Footwear'].url;
      if (imageSourceType === 'UPLOAD' && uploadedImagePreview) {
        visualAsset = uploadedImagePreview;
      } else if (imageSourceType === 'URL' && customImageUrl.trim()) {
        visualAsset = customImageUrl.trim();
      }

      const generated = {
        headline: `UNLEASH YOUR BEST: ${productName.toUpperCase()}`,
        primaryText: `Engineered specifically for ${targetAudience.toLowerCase()}, ${productName} by ${brandName} fuses cutting-edge performance with standout aesthetic design. ${sellingPoints}. ${promotionalOffer}!`,
        description: `Premium ${category} crafted for maximum impact. ${price ? `Starting at ₹${parseFloat(price).toLocaleString()}.` : ''} Fast dispatch & verified quality guarantee.`,
        cta: cta,
        promotionalWording: promotionalOffer,
        generatedVisualUrl: visualAsset,
        socialCaption: `🔥 Drop Alert! Meet the all-new ${productName} by #${brandName.replace(/\s+/g, '')}!\n\n✨ Built for ${targetAudience}\n🎯 ${promotionalOffer}\n⚡ ${sellingPoints}\n\n👉 Click "${cta}" to secure yours before this batch sells out!\n\n#${category.replace(/\s+/g, '')} #${productName.replace(/\s+/g, '')} #AdHunterAI #ViralCreative`,
        targetAudienceSuggestions: [
          `${targetAudience} actively engaging with ${category} brands`,
          `High-intent online shoppers located in ${location}`,
          `Trend-focused consumers looking for ${promotionalOffer}`
        ],
        videoScript: `[0:00 - 0:03 HOOK]: Fast kinetic visual of ${productName}. On-screen text: "Stop scrolling!"\n[0:03 - 0:08 PROBLEM/SOLUTION]: 3D cinematic showcase. Voiceover: "${brandName}'s new ${category.toLowerCase()} is here to change the game."\n[0:08 - 0:12 PROMO]: Split-screen showing special deal: "${promotionalOffer}"\n[0:12 - 0:15 CTA]: Bold red branding card: "Tap ${cta} now!"`,
        generatedAt: new Date().toISOString()
      };

      setGeneratedResult(generated);

      // Persist usage server-side and in user state
      const updatedUser = {
        ...user,
        freeAdsUsed: 1,
        freeAdsRemaining: 0,
        freeAdGenerated: true,
        generatedFreeAd: {
          productName,
          category,
          mediaUrl: visualAsset,
          ...generated
        }
      };

      dispatch(setCredentials({ user: updatedUser, token: 'mock-jwt-token' }));

      // Persist in local mock DB
      const mockUsers = JSON.parse(localStorage.getItem('mock_users') || '[]');
      const idx = mockUsers.findIndex((u: any) => u.email === user.email);
      if (idx !== -1) {
        mockUsers[idx] = updatedUser;
        localStorage.setItem('mock_users', JSON.stringify(mockUsers));
      }
    }, 2200);
  };


  const currentVisualUrl = generatedResult?.generatedVisualUrl || CATEGORY_AI_VISUALS[category]?.url || CATEGORY_AI_VISUALS['Footwear'].url;

  return (
    <div className="min-h-screen bg-white text-black font-sans selection:bg-red-600 selection:text-white py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* Top Header Card */}
        <div className="bg-zinc-50 border border-zinc-200 rounded-3xl p-6 sm:p-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-red-50 border border-red-200 text-red-600 text-xs font-black uppercase tracking-wider">
              <Sparkles className="w-3.5 h-3.5 text-red-600" />
              <span>Generative AI Ad Studio</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-black text-black font-display tracking-tight">
              Create Your <span className="text-red-600">1 Free AI Advertisement</span>
            </h1>
            <p className="text-xs sm:text-sm text-zinc-600 font-medium max-w-xl leading-relaxed">
              No images or files required. Simply enter your product attributes and our AI engine will generate complete photorealistic visual creatives, copy hooks, and social ad formats.
            </p>
          </div>

          <div className="p-4 bg-white border border-zinc-200 rounded-2xl shadow-sm space-y-1.5 shrink-0 text-center sm:text-left">
            <span className="text-[10px] font-black uppercase tracking-wider text-zinc-400 block">Explorer Entitlement</span>
            <div className="flex items-center gap-2">
              <span className={`px-2.5 py-1 rounded-lg text-xs font-black uppercase ${
                isFreeAdUsed ? 'bg-zinc-200 text-zinc-700' : 'bg-red-50 text-red-600 border border-red-200'
              }`}>
                {isFreeAdUsed ? '0 Free Ads Remaining (Claimed)' : '1 Free Ad Available'}
              </span>
            </div>
          </div>
        </div>

        {/* State Banner if Already Used */}
        {isFreeAdUsed && (
          <div className="bg-red-50 border border-red-200 rounded-2xl p-6 flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="space-y-1 text-center sm:text-left">
              <div className="flex items-center gap-2 text-red-700 font-black text-xs uppercase tracking-wider justify-center sm:justify-start">
                <AlertCircle className="w-4 h-4 text-red-600" />
                <span>Free Trial Limit Reached</span>
              </div>
              <p className="text-xs text-zinc-700 font-medium">
                You have claimed your 1 free advertisement. Want to generate more image ads, video reels, and launch automated campaigns?
              </p>
            </div>
            <button
              onClick={() => setShowConversionModal(true)}
              className="btn-shimmer px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-black text-xs uppercase tracking-wider rounded-xl shadow-md shadow-red-600/20 shrink-0"
            >
              <span>Create More Advertisements</span>
              <ArrowRight className="w-4 h-4 inline ml-1.5" />
            </button>
          </div>
        )}

        {/* Main 2-Column Grid: Form & Live Output Preview */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Column: Form (7 cols) */}
          <div className="lg:col-span-7 bg-white border border-zinc-200 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
            <div className="border-b border-zinc-100 pb-4">
              <h2 className="text-lg font-black text-black font-display">Product & Ad Creative Parameters</h2>
              <p className="text-xs text-zinc-500 font-medium mt-0.5">Describe your product and AI will synthesize the visual and copy.</p>
            </div>

            <form onSubmit={handleGenerate} className="space-y-6">
              
              {/* Section 1: Product Image & Visual Source Selection */}
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <label className="block text-xs font-bold uppercase tracking-wider text-zinc-700">
                    1. Product Image / Visual Source *
                  </label>
                  <span className="text-[10px] font-bold text-red-600 uppercase bg-red-50 px-2 py-0.5 rounded-md border border-red-100">
                    {imageSourceType === 'UPLOAD' ? 'Custom Upload Active' : imageSourceType === 'URL' ? 'Web URL Active' : 'AI Generation Active'}
                  </span>
                </div>

                {/* Source Selection Tabs */}
                <div className="grid grid-cols-3 gap-2 p-1.5 bg-zinc-100 rounded-2xl border border-zinc-200">
                  <button
                    type="button"
                    onClick={() => setImageSourceType('AI_STUDIO')}
                    className={`py-2.5 px-3 rounded-xl font-black text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-all ${
                      imageSourceType === 'AI_STUDIO'
                        ? 'bg-red-600 text-white shadow-sm shadow-red-600/20'
                        : 'text-zinc-600 hover:text-black hover:bg-zinc-200/60'
                    }`}
                  >
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>AI Visuals</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => setImageSourceType('UPLOAD')}
                    className={`py-2.5 px-3 rounded-xl font-black text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-all ${
                      imageSourceType === 'UPLOAD'
                        ? 'bg-red-600 text-white shadow-sm shadow-red-600/20'
                        : 'text-zinc-600 hover:text-black hover:bg-zinc-200/60'
                    }`}
                  >
                    <Upload className="w-3.5 h-3.5" />
                    <span>Upload Image</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => setImageSourceType('URL')}
                    className={`py-2.5 px-3 rounded-xl font-black text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-all ${
                      imageSourceType === 'URL'
                        ? 'bg-red-600 text-white shadow-sm shadow-red-600/20'
                        : 'text-zinc-600 hover:text-black hover:bg-zinc-200/60'
                    }`}
                  >
                    <Link2 className="w-3.5 h-3.5" />
                    <span>Image URL</span>
                  </button>
                </div>

                {/* Mode 1: AI Visual Themes */}
                {imageSourceType === 'AI_STUDIO' && (
                  <div className="space-y-2">
                    <span className="text-[10px] font-black uppercase tracking-wider text-zinc-400 block">
                      Choose AI Visual Lighting & Aesthetic Theme:
                    </span>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                      {AI_STYLE_THEMES.map((th) => (
                        <button
                          key={th.id}
                          type="button"
                          onClick={() => setSelectedStyle(th.id)}
                          className={`p-3.5 rounded-2xl border-2 text-left transition-all ${
                            selectedStyle === th.id 
                              ? 'border-red-600 bg-red-50/50 shadow-sm' 
                              : 'border-zinc-200 bg-zinc-50 hover:bg-white'
                          }`}
                        >
                          <span className="text-xs font-black text-black block">{th.name}</span>
                          <span className="text-[10px] text-zinc-500 font-medium leading-tight block mt-0.5">{th.desc}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {/* Mode 2: Direct File Upload */}
                {imageSourceType === 'UPLOAD' && (
                  <div className="space-y-3">
                    {!uploadedImagePreview ? (
                      <label className="border-2 border-dashed border-zinc-300 hover:border-red-600 rounded-3xl p-6 flex flex-col items-center justify-center cursor-pointer bg-zinc-50 hover:bg-red-50/30 transition-all group">
                        <div className="w-12 h-12 rounded-2xl bg-white border border-zinc-200 flex items-center justify-center text-zinc-500 group-hover:text-red-600 group-hover:border-red-200 shadow-sm mb-3 transition-colors">
                          <Upload className="w-5 h-5" />
                        </div>
                        <span className="text-xs font-black text-black group-hover:text-red-600">Click or drag & drop product photo</span>
                        <span className="text-[10px] text-zinc-400 font-semibold mt-1">Supports PNG, JPG, JPEG, WebP (Max 5MB)</span>
                        <input 
                          type="file" 
                          accept="image/png,image/jpeg,image/jpg,image/webp" 
                          onChange={handleImageUpload} 
                          className="hidden" 
                        />
                      </label>
                    ) : (
                      <div className="p-4 bg-zinc-50 border border-zinc-200 rounded-3xl flex items-center justify-between gap-4">
                        <div className="flex items-center gap-3">
                          <img 
                            src={uploadedImagePreview} 
                            alt="Uploaded product preview" 
                            className="w-16 h-16 rounded-2xl object-cover border border-zinc-200 shadow-sm"
                          />
                          <div>
                            <span className="text-xs font-black text-black block truncate max-w-[200px]">{uploadedFileName || 'product-image.jpg'}</span>
                            <span className="text-[10px] font-bold text-green-600 flex items-center gap-1 mt-0.5">
                              <CheckCircle2 className="w-3 h-3" /> Ready for AI Ad Composition
                            </span>
                          </div>
                        </div>

                        <button
                          type="button"
                          onClick={handleRemoveUploadedImage}
                          className="p-2.5 rounded-xl text-zinc-400 hover:text-red-600 hover:bg-red-50 transition-colors border border-zinc-200"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    )}
                  </div>
                )}

                {/* Mode 3: Image Web URL */}
                {imageSourceType === 'URL' && (
                  <div className="space-y-3">
                    <div>
                      <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Direct Image URL (HTTPS)</label>
                      <div className="relative">
                        <input
                          type="url"
                          value={customImageUrl}
                          onChange={(e) => setCustomImageUrl(e.target.value)}
                          placeholder="https://yourbrand.com/images/product.jpg"
                          className="w-full pl-10 pr-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                        />
                        <Link2 className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3.5" />
                      </div>
                    </div>

                    {customImageUrl.trim() && (
                      <div className="p-3 bg-zinc-50 border border-zinc-200 rounded-2xl flex items-center gap-3">
                        <img 
                          src={customImageUrl} 
                          alt="URL preview" 
                          onError={(e) => { (e.target as any).src = CATEGORY_AI_VISUALS['Footwear'].url; }}
                          className="w-12 h-12 rounded-xl object-cover border border-zinc-200 shadow-sm"
                        />
                        <div className="text-[11px] font-bold text-zinc-700 truncate">
                          Live image link preview loaded
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>


              {/* Section 2: Product Specifications */}
              <div className="space-y-4 pt-2">
                <span className="text-[10px] font-black uppercase tracking-wider text-zinc-400 block">2. Product Specifications</span>
                
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Product Category *</label>
                    <select
                      value={category}
                      onChange={(e) => handleCategoryChange(e.target.value)}
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                    >
                      <option value="Footwear">Footwear & Sneakers</option>
                      <option value="Apparel">Fashion & Apparel</option>
                      <option value="Electronics">Consumer Electronics & Audio</option>
                      <option value="Beauty">Skincare & Fragrance</option>
                      <option value="Fitness">Fitness & Athletic Gear</option>
                      <option value="Jewelry">Luxury Watches & Jewelry</option>
                      <option value="Home">Home & Modern Living</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Product Name *</label>
                    <input
                      type="text"
                      required
                      value={productName}
                      onChange={(e) => setProductName(e.target.value)}
                      placeholder="e.g. Velocity Hyper-Glide X1"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Price (₹)</label>
                    <input
                      type="number"
                      value={price}
                      onChange={(e) => setPrice(e.target.value)}
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Brand Name</label>
                    <input
                      type="text"
                      value={brandName}
                      onChange={(e) => setBrandName(e.target.value)}
                      placeholder="e.g. Velocity Athletics"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Target Audience *</label>
                  <input
                    type="text"
                    required
                    value={targetAudience}
                    onChange={(e) => setTargetAudience(e.target.value)}
                    placeholder="e.g. Marathon runners, fitness creators, urban millennials"
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Product Description / Highlights</label>
                  <input
                    type="text"
                    value={productDesc}
                    onChange={(e) => setProductDesc(e.target.value)}
                    placeholder="e.g. Carbon-fiber race shoes engineered for velocity and comfort"
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Target Geo Location</label>
                  <input
                    type="text"
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    placeholder="e.g. India (Metro Tier 1 & 2 cities)"
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                  />
                </div>
              </div>

              {/* Section 3: Copywriting Directives */}
              <div className="space-y-4 pt-2">
                <span className="text-[10px] font-black uppercase tracking-wider text-zinc-400 block">3. Marketing Directives</span>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Ad Purpose / Goal *</label>
                    <select
                      value={objective}
                      onChange={(e) => setObjective(e.target.value)}
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                    >
                      <option value="Product Sales & Purchases">Product Sales & Purchases</option>
                      <option value="Brand Discovery & Reach">Brand Discovery & Reach</option>
                      <option value="New Product Showcase">New Product Showcase</option>
                      <option value="Flash Discount Offer">Flash Discount Offer</option>
                    </select>
                  </div>


                  <div>
                    <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Call To Action (CTA) *</label>
                    <select
                      value={cta}
                      onChange={(e) => setCta(e.target.value)}
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                    >
                      <option value="Shop Now">Shop Now</option>
                      <option value="Order Today">Order Today</option>
                      <option value="Claim 30% Off">Claim 30% Off</option>
                      <option value="Get Free Trial">Get Free Trial</option>
                      <option value="Book Consultation">Book Consultation</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Advertisement Tone *</label>
                    <select
                      value={tone}
                      onChange={(e) => setTone(e.target.value)}
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                    >
                      <option value="High Energy & Urgent">High Energy & Urgent</option>
                      <option value="Premium & Sophisticated">Premium & Sophisticated</option>
                      <option value="Playful & Fun">Playful & Fun</option>
                      <option value="Direct & Professional">Direct & Professional</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Promotional Offer Hook</label>
                  <input
                    type="text"
                    value={promotionalOffer}
                    onChange={(e) => setPromotionalOffer(e.target.value)}
                    placeholder="e.g. FLAT 30% OFF + Free Express Shipping"
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold uppercase text-zinc-600 mb-1">Key Selling Points</label>
                  <textarea
                    rows={2}
                    value={sellingPoints}
                    onChange={(e) => setSellingPoints(e.target.value)}
                    placeholder="e.g. Carbon-fiber spring plate, 48-hr flash dispatch, 100% money-back guarantee..."
                    className="w-full p-3 bg-zinc-50 border border-zinc-300 rounded-xl font-bold text-xs text-black focus:outline-none focus:border-red-600"
                  />
                </div>
              </div>

              {/* Submit CTA */}
              <div className="pt-4 border-t border-zinc-100">
                <button
                  type="submit"
                  disabled={isGenerating || isFreeAdUsed}
                  className={`btn-shimmer w-full py-4 rounded-2xl font-black text-xs uppercase tracking-wider transition-all flex items-center justify-center gap-2 shadow-md ${
                    isFreeAdUsed
                      ? 'bg-zinc-200 text-zinc-500 cursor-not-allowed border border-zinc-300'
                      : 'bg-red-600 hover:bg-red-700 text-white shadow-red-600/20'
                  }`}
                >
                  {isGenerating ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin text-white" />
                      <span>AI Generative Studio Rendering... (Step {generationStep}/3)</span>
                    </>
                  ) : isFreeAdUsed ? (
                    <>
                      <Lock className="w-4 h-4" />
                      <span>Free Trial Ad Already Used</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      <span>Generate 1 Free AI Advertisement</span>
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
              </div>

            </form>
          </div>

          {/* Right Column: Live Output & Social Previews (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* Social Platform Switcher */}
            <div className="bg-white border border-zinc-200 rounded-3xl p-5 shadow-sm space-y-4">
              <div className="flex justify-between items-center">
                <span className="text-xs font-black text-black font-display uppercase tracking-wider">Social Ad Preview Simulator</span>
                <span className="text-[10px] font-mono font-black text-red-600 px-2 py-0.5 bg-red-50 rounded-md">LIVE</span>
              </div>

              <div className="grid grid-cols-3 gap-2 bg-zinc-100 p-1 rounded-2xl">
                <button
                  type="button"
                  onClick={() => setActivePreviewTab('INSTAGRAM')}
                  className={`py-2 rounded-xl text-[11px] font-black uppercase transition-all ${
                    activePreviewTab === 'INSTAGRAM' ? 'bg-red-600 text-white shadow-sm' : 'text-zinc-600 hover:text-black'
                  }`}
                >
                  Instagram
                </button>
                <button
                  type="button"
                  onClick={() => setActivePreviewTab('TIKTOK')}
                  className={`py-2 rounded-xl text-[11px] font-black uppercase transition-all ${
                    activePreviewTab === 'TIKTOK' ? 'bg-red-600 text-white shadow-sm' : 'text-zinc-600 hover:text-black'
                  }`}
                >
                  TikTok Reel
                </button>
                <button
                  type="button"
                  onClick={() => setActivePreviewTab('FACEBOOK')}
                  className={`py-2 rounded-xl text-[11px] font-black uppercase transition-all ${
                    activePreviewTab === 'FACEBOOK' ? 'bg-red-600 text-white shadow-sm' : 'text-zinc-600 hover:text-black'
                  }`}
                >
                  Facebook
                </button>
              </div>

              {/* Mock Phone Frame / Feed Card */}
              <div className="border border-zinc-200 rounded-2xl overflow-hidden bg-white shadow-md">
                
                {/* Post Header */}
                <div className="p-3 border-b border-zinc-100 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-full bg-red-600 text-white font-black text-xs flex items-center justify-center shadow-sm">
                      {brandName.substring(0, 1) || 'A'}
                    </div>
                    <div>
                      <span className="text-xs font-black text-black block leading-none">{brandName || 'Brand Partner'}</span>
                      <span className="text-[9px] text-zinc-400 font-medium">Sponsored · AI Optimized</span>
                    </div>
                  </div>
                  <span className="text-zinc-400 font-bold">•••</span>
                </div>

                {/* Creative Asset Display (Photorealistic AI Graphic) */}
                <div className="relative bg-zinc-950 aspect-square flex items-center justify-center overflow-hidden group">
                  <img
                    src={currentVisualUrl}
                    alt="AI Generated Creative"
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  
                  {/* Overlay Offer Hook Badge */}
                  <div className="absolute top-3 left-3 bg-red-600/90 backdrop-blur-md text-white px-3 py-1 rounded-full text-[10px] font-black tracking-wider shadow-lg">
                    {promotionalOffer || 'SPECIAL LAUNCH OFFER'}
                  </div>

                  {activePreviewTab === 'TIKTOK' && (
                    <div className="absolute inset-0 bg-black/30 flex items-center justify-center">
                      <div className="w-12 h-12 rounded-full bg-white/90 text-black flex items-center justify-center shadow-xl">
                        ▶
                      </div>
                    </div>
                  )}
                </div>

                {/* Action Button Bar */}
                <div className="p-3 border-t border-zinc-100 flex items-center justify-between bg-zinc-50">
                  <div>
                    <span className="text-[10px] font-black uppercase text-zinc-500 block">Headline</span>
                    <span className="text-xs font-black text-black truncate max-w-[200px] block">
                      {generatedResult?.headline || (productName ? `UPGRADE TO ${productName.toUpperCase()}` : 'EXPERIENCE THE DIFFERENCE')}
                    </span>
                  </div>
                  <span className="btn-shimmer px-4 py-1.5 bg-red-600 text-white font-black text-[11px] uppercase rounded-xl shadow-sm">
                    {cta}
                  </span>
                </div>

                {/* Post Caption Body */}
                <div className="p-3.5 space-y-2 text-xs">
                  <div className="flex items-center gap-4 text-zinc-600 pb-1">
                    <Heart className="w-4 h-4 text-red-600" />
                    <MessageCircle className="w-4 h-4" />
                    <Send className="w-4 h-4" />
                    <Bookmark className="w-4 h-4 ml-auto" />
                  </div>
                  <p className="text-zinc-800 leading-relaxed font-medium">
                    <strong className="text-black font-black mr-1.5">{brandName}</strong>
                    {generatedResult?.primaryText || (productName ? `Looking for top quality ${category.toLowerCase()}? ${productName} brings unmatched design and durability.` : 'Fill the parameters on the left to see the AI generate your campaign copy.')}
                  </p>
                </div>

              </div>

            </div>

            {/* Generated Script / Audience Cards if Result Exists */}
            {generatedResult && (
              <div className="bg-zinc-50 border border-zinc-200 rounded-3xl p-6 space-y-4 animate-in fade-in duration-300">
                <div className="flex items-center gap-2 text-xs font-black text-black font-display uppercase">
                  <CheckCircle2 className="w-4 h-4 text-red-600" />
                  <span>AI Multimodal Deliverables</span>
                </div>

                <div className="p-4 bg-white border border-zinc-200 rounded-2xl space-y-2">
                  <span className="text-[10px] font-black uppercase text-zinc-400 block">Suggested Audience Targets</span>
                  <ul className="space-y-1.5 text-xs font-semibold text-zinc-800">
                    {generatedResult.targetAudienceSuggestions?.map((item: string, idx: number) => (
                      <li key={idx} className="flex items-center gap-2">
                        <Check className="w-3.5 h-3.5 text-red-600 shrink-0" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {generatedResult.videoScript && (
                  <div className="p-4 bg-white border border-zinc-200 rounded-2xl space-y-2">
                    <span className="text-[10px] font-black uppercase text-zinc-400 block">15s Dynamic Video Script</span>
                    <pre className="text-[11px] text-zinc-700 font-mono whitespace-pre-wrap leading-relaxed">
                      {generatedResult.videoScript}
                    </pre>
                  </div>
                )}

                {/* Conversion Trigger */}
                <div className="pt-2">
                  <button
                    onClick={() => setShowConversionModal(true)}
                    className="btn-shimmer w-full py-3.5 rounded-2xl bg-black hover:bg-zinc-900 text-white font-black text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-md"
                  >
                    <span>Create More Campaigns (Choose B2B / B2C)</span>
                    <ArrowRight className="w-4 h-4 text-red-500" />
                  </button>
                </div>
              </div>
            )}

          </div>

        </div>

        {/* CONVERSION MODAL: Steers Explorer into B2B or B2C */}
        {showConversionModal && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-in fade-in duration-200">
            <div className="bg-white rounded-3xl p-8 max-w-xl w-full shadow-2xl border border-zinc-200 animate-in zoom-in-95 duration-200 space-y-6">
              <div className="flex justify-between items-start">
                <div>
                  <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-red-50 border border-red-200 text-red-600 text-[10px] font-black uppercase tracking-wider mb-2">
                    <span>Explorer Conversion</span>
                  </div>
                  <h2 className="text-2xl font-black text-black font-display tracking-tight">Unlock Unlimited Ad Creation</h2>
                  <p className="text-xs text-zinc-600 font-medium mt-1">
                    Select your permanent commercial account type to unlock full studio capabilities, campaign management, and pricing plans.
                  </p>
                </div>
                <button onClick={() => setShowConversionModal(false)} className="text-zinc-400 hover:text-black font-bold p-1">✕</button>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Link
                  to="/profile?edit=true&type=B2B"
                  className="p-5 rounded-2xl border-2 border-zinc-200 hover:border-red-600 bg-zinc-50 hover:bg-white text-left transition-all group flex flex-col justify-between space-y-3"
                >
                  <div className="space-y-1">
                    <div className="w-10 h-10 rounded-xl bg-black text-white flex items-center justify-center">
                      <Building2 className="w-5 h-5 text-red-500" />
                    </div>
                    <h3 className="text-sm font-black text-black font-display pt-1">B2B Business SaaS</h3>
                    <p className="text-[11px] text-zinc-600 font-medium">Self-serve multi-product management, automated campaigns, and direct Meta/TikTok API dispatch.</p>
                  </div>
                  <span className="text-xs font-black text-red-600 flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                    Select B2B <ArrowRight className="w-3 h-3" />
                  </span>
                </Link>

                <Link
                  to="/profile?edit=true&type=B2C"
                  className="p-5 rounded-2xl border-2 border-zinc-200 hover:border-red-600 bg-red-50/30 hover:bg-white text-left transition-all group flex flex-col justify-between space-y-3"
                >
                  <div className="space-y-1">
                    <div className="w-10 h-10 rounded-xl bg-red-600 text-white flex items-center justify-center">
                      <ShoppingBag className="w-5 h-5" />
                    </div>
                    <h3 className="text-sm font-black text-black font-display pt-1">B2C Creative Client</h3>
                    <p className="text-[11px] text-zinc-600 font-medium">Done-For-You 4K image creatives, viral video reels, and dedicated advertising director.</p>
                  </div>
                  <span className="text-xs font-black text-red-600 flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                    Select B2C <ArrowRight className="w-3 h-3" />
                  </span>
                </Link>
              </div>

              <div className="bg-zinc-50 border border-zinc-200 rounded-2xl p-4 text-[11px] text-zinc-600 font-medium text-center">
                💡 Clicking an option will open your Profile Editor. You must click <strong>[Save Profile Changes]</strong> to confirm your permanent account type.
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
